// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGp9Ya9ZiuduriS3LwtMgc0vDYU7j0vj8',
    appId: '1:799496228590:web:b93607b58f31c94cc0edff',
    messagingSenderId: '799496228590',
    projectId: 'project-a633b',
    authDomain: 'project-a633b.firebaseapp.com',
    databaseURL: 'https://project-a633b.firebaseio.com',
    storageBucket: 'project-a633b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAETo8_62X8bSHsXEHUVCxIjCTlxGGhZAg',
    appId: '1:799496228590:android:6610d3ffe783df6ac0edff',
    messagingSenderId: '799496228590',
    projectId: 'project-a633b',
    databaseURL: 'https://project-a633b.firebaseio.com',
    storageBucket: 'project-a633b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoBfwwgxwGyI-AAqWPgKei_1expqzuArk',
    appId: '1:799496228590:ios:6223b0a52dc5a520c0edff',
    messagingSenderId: '799496228590',
    projectId: 'project-a633b',
    databaseURL: 'https://project-a633b.firebaseio.com',
    storageBucket: 'project-a633b.firebasestorage.app',
    iosClientId: '799496228590-qkjdq1veuhpq2h4shfm4e2n54qjbs1lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.mainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoBfwwgxwGyI-AAqWPgKei_1expqzuArk',
    appId: '1:799496228590:ios:6223b0a52dc5a520c0edff',
    messagingSenderId: '799496228590',
    projectId: 'project-a633b',
    databaseURL: 'https://project-a633b.firebaseio.com',
    storageBucket: 'project-a633b.firebasestorage.app',
    iosClientId: '799496228590-qkjdq1veuhpq2h4shfm4e2n54qjbs1lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.mainApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGp9Ya9ZiuduriS3LwtMgc0vDYU7j0vj8',
    appId: '1:799496228590:web:8a420c317d722133c0edff',
    messagingSenderId: '799496228590',
    projectId: 'project-a633b',
    authDomain: 'project-a633b.firebaseapp.com',
    databaseURL: 'https://project-a633b.firebaseio.com',
    storageBucket: 'project-a633b.firebasestorage.app',
  );

}